services:
    arturdoruch_list.templating.pagination_helper:
        class: ArturDoruch\ListBundle\Templating\PaginationHelper
        autowire: true
        arguments:
            $pageItemsConfig: '%arturdoruch_list.pagination.page_items%'
            $itemLimits: '%arturdoruch_list.pagination.item_limits%'

    arturdoruch_list.twig.pagination_extension:
        class: ArturDoruch\ListBundle\Twig\Extension\PaginationExtension
        autowire: true
        tags:
            - { name: twig.extension }

    arturdoruch_list.twig.filter_extension:
        class: ArturDoruch\ListBundle\Twig\Extension\FilteringExtension
        autowire: true
        tags:
            - { name: twig.extension }

    arturdoruch_list.twig.sorting_extension:
        class: ArturDoruch\ListBundle\Twig\Extension\SortingExtension
        autowire: true
        tags:
            - { name: twig.extension }